id: P010313
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18550
  title: སྦྱོར་བ་སྨན།
  author: ''
  volumes:
    a380e42ef80846b5a4dac56f8d0f6b0a:
      image_group_id: I8LS18552
      title: ''
      volume_number: 1
      total_pages: 313
