id: I61595567
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:11:12+00:00'
last_modified: '2022-06-08T12:40:30.679712+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18550
  title: སྦྱོར་བ་སྨན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    3D04:
      image_group_id: I8LS18552
      title: ''
      total_pages: 313
      order: 1
      base_file: 3D04.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
